import math
import os
import tkinter as tk
from tkinter import filedialog, messagebox
from collections import Counter

import ezdxf
from ezdxf.path import make_path


# -----------------------------
# Helpers
# -----------------------------
def dist(a, b):
    return math.hypot(b[0] - a[0], b[1] - a[1])


def sort_paths_nearest(paths):
    """
    Simple greedy ordering:
    start with first path, then pick the next path whose start/end is nearest
    to the current end. Reduces air travel.
    """
    if not paths:
        return []

    remaining = paths[:]
    ordered = [remaining.pop(0)]

    while remaining:
        last_end = ordered[-1][-1]
        best_i = None
        best_reverse = False
        best_d = float("inf")

        for i, p in enumerate(remaining):
            d_start = dist(last_end, p[0])
            d_end = dist(last_end, p[-1])
            if d_start < best_d:
                best_d = d_start
                best_i = i
                best_reverse = False
            if d_end < best_d:
                best_d = d_end
                best_i = i
                best_reverse = True

        nxt = remaining.pop(best_i)
        if best_reverse:
            nxt = list(reversed(nxt))
        ordered.append(nxt)

    return ordered


def debug_entity_types(doc):
    """Print entity-type counts to console (handy when a file won’t convert)."""
    msp = doc.modelspace()
    c = Counter(e.dxftype() for e in msp)
    print("Entity types in modelspace:")
    for k, v in c.most_common():
        print(f"  {k:16s} {v}")


def iter_entities_with_inserts(layout):
    """
    Yield normal entities plus the expanded (virtual) contents of INSERT block refs.
    Many 'art DXF' files are mostly INSERTs (blocks).
    """
    for e in layout:
        if e.dxftype() == "INSERT":
            try:
                for ve in e.virtual_entities():
                    yield ve
            except Exception:
                # Some inserts can be weird; ignore if they won't virtualise
                continue
        else:
            yield e


# -----------------------------
# DXF → Paths (robust)
# -----------------------------
def extract_paths(doc, seg_len=0.5):
    """
    Convert a DXF to a list of paths, where each path is a list of (x,y) points.

    Uses ezdxf.path.make_path() to support many entity types:
    LINE, ARC, CIRCLE, ELLIPSE, SPLINE, HATCH boundaries, etc.
    Also expands INSERT block references via virtual_entities().

    seg_len controls curve flattening resolution:
    smaller = smoother curves but more points & bigger G-code.
    """
    msp = doc.modelspace()
    paths = []

    for e in iter_entities_with_inserts(msp):
        try:
            p = make_path(e)
        except TypeError:
            # Unsupported entity type
            continue
        except Exception:
            # Any other geometry conversion issue
            continue

        # Path can contain multiple subpaths (e.g. HATCH boundaries)
        try:
            subpaths = p.sub_paths()
        except Exception:
            subpaths = [p]

        for sp in subpaths:
            try:
                pts = [(v.x, v.y) for v in sp.flattening(distance=float(seg_len))]
            except Exception:
                continue

            # De-dupe immediate repeats (helps with tiny segments)
            cleaned = []
            for pt in pts:
                if not cleaned or (abs(pt[0] - cleaned[-1][0]) > 1e-9 or abs(pt[1] - cleaned[-1][1]) > 1e-9):
                    cleaned.append(pt)

            if len(cleaned) >= 2:
                paths.append(cleaned)

    return paths


# -----------------------------
# G-code generation (GRBL-ish)
# -----------------------------
def generate_gcode(
    paths,
    out_path,
    units="mm",
    scale=1.0,
    feed_xy=600.0,
    feed_z=200.0,
    safe_z=5.0,
    cut_z=-0.5,
    spindle_rpm=10000,
    spindle_on=True,
):
    lines = []
    lines.append("(DXF to G-code for 3018 / GRBL)")
    lines.append("(Generated by Python converter)")
    lines.append("G90 (absolute positioning)")
    lines.append("G21 (mm)") if units == "mm" else lines.append("G20 (inch)")
    lines.append("G17 (XY plane)")
    lines.append(f"G0 Z{safe_z:.4f}")

    if spindle_on:
        lines.append(f"M3 S{int(spindle_rpm)}")

    for path in paths:
        if len(path) < 2:
            continue

        # Rapid to start at safe Z
        sx, sy = path[0]
        sx *= scale
        sy *= scale
        lines.append(f"G0 X{sx:.4f} Y{sy:.4f}")
        lines.append(f"G1 Z{cut_z:.4f} F{feed_z:.2f}")

        # Cut moves
        for x, y in path[1:]:
            x *= scale
            y *= scale
            lines.append(f"G1 X{x:.4f} Y{y:.4f} F{feed_xy:.2f}")

        # Retract
        lines.append(f"G0 Z{safe_z:.4f}")

    if spindle_on:
        lines.append("M5")

    lines.append("G0 X0 Y0")
    lines.append("M2")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# -----------------------------
# GUI
# -----------------------------
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("DXF → G-code (3018 / GRBL)")
        self.geometry("700x520")

        self.dxf_path = tk.StringVar()
        self.out_path = tk.StringVar()

        self.units = tk.StringVar(value="mm")
        self.scale = tk.DoubleVar(value=1.0)
        self.seg_len = tk.DoubleVar(value=0.8)  # slightly higher default to avoid massive gcode

        self.feed_xy = tk.DoubleVar(value=600.0)
        self.feed_z = tk.DoubleVar(value=200.0)
        self.safe_z = tk.DoubleVar(value=5.0)
        self.cut_z = tk.DoubleVar(value=-0.5)

        self.spindle_on = tk.BooleanVar(value=True)
        self.spindle_rpm = tk.IntVar(value=10000)

        self.sort_paths = tk.BooleanVar(value=True)
        self.show_debug = tk.BooleanVar(value=False)

        self._build()

    def _build(self):
        pad = {"padx": 10, "pady": 6}

        frm = tk.Frame(self)
        frm.pack(fill="both", expand=True)

        # DXF picker
        tk.Label(frm, text="DXF file:").grid(row=0, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.dxf_path, width=60).grid(row=0, column=1, sticky="we", **pad)
        tk.Button(frm, text="Browse…", command=self.browse_dxf).grid(row=0, column=2, **pad)

        # Output picker
        tk.Label(frm, text="Output G-code (optional):").grid(row=1, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.out_path, width=60).grid(row=1, column=1, sticky="we", **pad)
        tk.Button(frm, text="Browse…", command=self.browse_out).grid(row=1, column=2, **pad)

        # Settings header
        tk.Label(frm, text="Settings", font=("Segoe UI", 11, "bold")).grid(row=2, column=0, columnspan=3, sticky="w", **pad)

        # Units + scale
        tk.Label(frm, text="Units:").grid(row=3, column=0, sticky="w", **pad)
        tk.OptionMenu(frm, self.units, "mm", "inch").grid(row=3, column=1, sticky="w", **pad)

        tk.Label(frm, text="Scale:").grid(row=4, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.scale).grid(row=4, column=1, sticky="w", **pad)

        # Curve flattening
        tk.Label(frm, text="Curve segment length (smaller = smoother):").grid(row=5, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.seg_len).grid(row=5, column=1, sticky="w", **pad)

        # Feeds
        tk.Label(frm, text="Feed XY (mm/min):").grid(row=6, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.feed_xy).grid(row=6, column=1, sticky="w", **pad)

        tk.Label(frm, text="Feed Z (mm/min):").grid(row=7, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.feed_z).grid(row=7, column=1, sticky="w", **pad)

        # Z
        tk.Label(frm, text="Safe Z (mm):").grid(row=8, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.safe_z).grid(row=8, column=1, sticky="w", **pad)

        tk.Label(frm, text="Cut Z (mm):").grid(row=9, column=0, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.cut_z).grid(row=9, column=1, sticky="w", **pad)

        # Spindle
        tk.Checkbutton(frm, text="Spindle on (M3/M5)", variable=self.spindle_on).grid(row=10, column=0, sticky="w", **pad)
        tk.Label(frm, text="Spindle RPM (S):").grid(row=10, column=1, sticky="w", **pad)
        tk.Entry(frm, textvariable=self.spindle_rpm, width=10).grid(row=10, column=2, sticky="w", **pad)

        # Options
        tk.Checkbutton(frm, text="Sort paths (reduce travel)", variable=self.sort_paths).grid(row=11, column=0, sticky="w", **pad)
        tk.Checkbutton(frm, text="Print DXF entity debug to console", variable=self.show_debug).grid(row=11, column=1, sticky="w", **pad)

        # Convert button
        tk.Button(frm, text="Convert", command=self.convert, height=2).grid(
            row=12, column=0, columnspan=3, sticky="we", padx=10, pady=14
        )

        # Notes
        note = (
            "Notes:\n"
            "• This traces DXF vectors (engrave / 2.5D). Not a full CAM tool (no pockets/profiles/tool comp).\n"
            "• If your G-code is enormous, increase “Curve segment length” (e.g. 1.0–2.0).\n"
            "• If size looks wrong, your DXF units are different — tweak Units or Scale.\n"
        )
        tk.Label(frm, text=note, justify="left").grid(row=13, column=0, columnspan=3, sticky="w", **pad)

        frm.grid_columnconfigure(1, weight=1)

    def browse_dxf(self):
        p = filedialog.askopenfilename(filetypes=[("DXF files", "*.dxf"), ("All files", "*.*")])
        if p:
            self.dxf_path.set(p)
            base = os.path.splitext(p)[0]
            self.out_path.set(base + ".gcode")

    def browse_out(self):
        p = filedialog.asksaveasfilename(defaultextension=".gcode", filetypes=[("G-code", "*.gcode"), ("All files", "*.*")])
        if p:
            self.out_path.set(p)

    def convert(self):
        dxf = self.dxf_path.get().strip()
        outp = self.out_path.get().strip()

        if not dxf:
            messagebox.showerror("Missing DXF", "Pick a DXF file first.")
            return
        if not os.path.exists(dxf):
            messagebox.showerror("DXF not found", "That DXF path doesn’t exist.")
            return
        if not outp:
            outp = os.path.splitext(dxf)[0] + ".gcode"
            self.out_path.set(outp)

        try:
            doc = ezdxf.readfile(dxf)

            if self.show_debug.get():
                debug_entity_types(doc)

            paths = extract_paths(doc, seg_len=float(self.seg_len.get()))
            if not paths:
                messagebox.showerror(
                    "No geometry found",
                    "Couldn’t extract any drawable paths.\n\n"
                    "Tick “Print DXF entity debug to console” and try again — "
                    "then share the entity list."
                )
                return

            if self.sort_paths.get():
                paths = sort_paths_nearest(paths)

            generate_gcode(
                paths=paths,
                out_path=outp,
                units=self.units.get(),
                scale=float(self.scale.get()),
                feed_xy=float(self.feed_xy.get()),
                feed_z=float(self.feed_z.get()),
                safe_z=float(self.safe_z.get()),
                cut_z=float(self.cut_z.get()),
                spindle_rpm=int(self.spindle_rpm.get()),
                spindle_on=bool(self.spindle_on.get()),
            )

            messagebox.showinfo("Done", f"Saved G-code:\n{outp}")

        except Exception as e:
            messagebox.showerror("Conversion failed", str(e))


if __name__ == "__main__":
    App().mainloop()
